# site settings
url: http://tedxparisdauphine.com
title: TEDx Université Paris-Dauphine - Conférences TEDx à l'université Paris-Dauphine
description: >
  TEDx Université Paris-Dauphine est une association dont l'objectif est d’organiser des conférences de façon indépendante sous licence TED afin de favoriser la diffusion d’idées au sein de l'Université Paris-Dauphine.
image: /assets/images/tedx-dauphine-home-background.jpg
selling: false
ticketing-url: https://www.weezevent.com/tedx-universite-paris-dauphine-2017-envie
fb-event-url: https://www.facebook.com/events/1981742498750762/

collections:
  videos:
    output: true
    permalink: /:collection/edition-:name/

defaults:
  - scope:
      path: ""
      type: videos
    values:
      layout: videos
      youtube-embed: true
  - scope:
      path: "_pages/home.html"
    values:
      netlify-identity: true

# build settings
permalink: pretty
include: ['_pages', '_redirects']
exclude: ['README.md']

sass:
  sass_dir: _sass
  style: compressed